# Shell variables
# Generated by 'wal'
wallpaper='/home/awala/Pictures/wallpapers/wallpaper_3.jpg'

# Special
background='#0F161C'
foreground='#c0cbcb'
cursor='#c0cbcb'

# Colors
color0='#0F161C'
color1='#50696F'
color2='#9D632C'
color3='#F59E0A'
color4='#5B7C83'
color5='#5F8188'
color6='#68888D'
color7='#c0cbcb'
color8='#868e8e'
color9='#50696F'
color10='#9D632C'
color11='#F59E0A'
color12='#5B7C83'
color13='#5F8188'
color14='#68888D'
color15='#c0cbcb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
