import = ["/home/awala/.config/alacritty/themes/themes/Cobalt2.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"
