theme = "dracula"

[editor]
auto-completion = true
cursorline = true
color-modes = true
line-number = "relative"
middle-click-paste = true
idle-timeout = 0
completion-trigger-len = 1

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-k = ["scroll_up"]
C-j = ["scroll_down"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
C-backspace = ["delete_word_backward"]
