#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## Script for spotify for waybar

combi="$(playerctl -p spotify status)$(playerctl status)"


case $combi in 
    "PlayingPlaying"|"PlayingPaused"|"PlayingStopped"|"PausedPaused"|"PausedStopped")
      player_status=$(playerctl -p spotify status)
      artist=$(playerctl -p spotify metadata artist)
      title=$(playerctl -p spotify metadata title)
      ;;
    *)
      player_status=$(playerctl status)
      artist=$(playerctl metadata artist)
      title=$(playerctl metadata title)
      ;;
esac

if [ "$player_status" = "Playing" ]; then
    echo -e " $artist - $title\nPlaying: $artist - $title\nplaying"
elif [ "$player_status" = "Paused" ]; then
    echo -e " $artist - $title\nPaused: $artist - $title\npaused"
else
    echo -e " Spotify Offline!\nSpotify Offline.\noffline"
fi
